Vue.component('pane',{
    name:'pane',
    template:'\
        <div class="pane" v-show="show">\
            <slot>父组件没东西默认显示我</slot>\
        </div>',
    props:{
        name:{
            type:String
        },
        label:{
            type:String,
            default:''
         },
    },
    data:function(){
        return {
            show:true
        }
    },
    methods:{
        updateNav:function(){
            this.$parent.updateNav();
        }
    },
    watch:{
        label:function(){
            this.updateNav();
        }
    },
    mounted:function(){
        this.updateNav();
    }
});